services:
  web:
    build: .
    container_name: django_app
    restart: always
    volumes:
      - static_volume:/app/static
      - sqlite_data:/app/data  
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  static_volume:
  sqlite_data: 
